# Government Timeline — Build Process

Builds `government_timeline.json`: one row per continuous PM tenure under a
single electoral mandate. Entries are split where a PM won re-election, or
where a government changed composition mid-parliament without an election.

**This notebook does not run cleanly top to bottom.** Two points require
manual intervention outside the code:

1. After the cell that exports `pm_timeline_working.xlsx` and
   `election_data.xlsx`, the timeline file was filled in by hand in Excel —
   election dates, own_mandate, opposition_party, coalition_parties — using
   the sources listed in the folder README. That edited file is what the
   later cells read back in.
2. The final cell merges in `end_reason` and `notes` from `text.txt`, which
   was generated separately using Gemini 3.1 Pro, not written here.

See the folder README for the full source list and file inventory.

## Election Data

In [1]:
import pandas as pd

df = pd.read_excel('Book1.ods', engine='odf')
print(df.head())

ImportError: `Import odfpy` failed.  Use pip or conda to install the odfpy package.

In [10]:
# Drop the sub-header row
df = df.drop(index=0).reset_index(drop=True)

# Rename columns cleanly
df.columns = [
    'election_date', 'total_seats',
    'con_votes', 'con_seats',
    'lab_votes', 'lab_seats',
    'lib_votes', 'lib_seats',
    'oth_votes', 'oth_seats',
    'comment'
]

print(df.head())

         election_date total_seats con_votes con_seats lab_votes lab_seats  \
0  1910-12-19 00:00:00         670      46.3       272       7.2        42
1  1918-12-14 00:00:00         707      38.7       383      23.7        73
2  1922-11-15 00:00:00         615      38.2       345      29.5       142
3  1923-12-06 00:00:00         615      38.1       258      30.5       191
4  1924-10-29 00:00:00         615      48.3       419        33       151

  lib_votes lib_seats oth_votes oth_seats  \
0      43.8       272       2.7        84
1      25.6       161        12        90
2      29.1       116       3.2        12
3      29.6       159       1.8         7
4      17.6        40       1.1         5

                                             comment
0  Repeat election forced by George V to legitimi...
1        Lloyd George (Lib) leads coalition with Con
2  Bonar Law (Con) breaks the coalition, Labour o...
3  Ramsay MacDonald (Lab) with Lib-coalition beat...
4  Baldwin (Con) elected after Liberals bring dow...

In [ ]:
df['election_date'] = pd.to_datetime(df['election_date']).dt.strftime('%Y-%m-%d')

numeric_cols = ['total_seats', 'con_votes', 'con_seats', 'lab_votes', 'lab_seats', 
                'lib_votes', 'lib_seats', 'oth_votes', 'oth_seats']
df[numeric_cols] = df[numeric_cols].apply(pd.to_numeric, errors='coerce')

In [35]:
election_df = df.copy()

## Timeline table

In [14]:
import pandas as pd

columns = [
    'pm',
    'party',
    'election_date',
    'own_mandate',
    'seats_won',
    'total_seats',
    'majority',
    'majority_end',
    'opposition_party',
    'coalition_parties',
    'pm_end_date',
    'resignation_date',
    'end_reason',
    'resignation',
    'notes'
]

df_timeline = pd.DataFrame(columns=columns)
print(df_timeline)

Empty DataFrame
Columns: [pm, party, election_date, own_mandate, seats_won, total_seats, majority, majority_end, opposition_party, coalition_parties, pm_end_date, resignation_date, end_reason, resignation, notes]
Index: []

## Primemister data

In [29]:
import pandas as pd
import requests
from io import StringIO

url = "https://en.wikipedia.org/wiki/List_of_prime_ministers_of_the_United_Kingdom"

headers = {
    "User-Agent": "Mozilla/5.0"
}

response = requests.get(url, headers=headers)

html = StringIO(response.text)

tables = pd.read_html(html)

print(len(tables))
print(tables[0].head())

4
  Portrait                                Prime ministerOffice(lifespan)  \
  Portrait Portrait.1                     Prime ministerOffice(lifespan)
0        ​        NaN  Robert Walpole[26]MP for King's Lynn (to 1742)...
1        ​        NaN  Robert Walpole[26]MP for King's Lynn (to 1742)...
2        ​        NaN  Robert Walpole[26]MP for King's Lynn (to 1742)...
3        ​        NaN  Robert Walpole[26]MP for King's Lynn (to 1742)...
4        ​        NaN  Spencer Compton[27]1st Earl of Wilmington(1673...

     Term of office                                        Mandate[a]  \
              Start               End             Duration Mandate[a]
0      3 April 1721  11 February 1742   20 years, 315 days       1722
1      3 April 1721  11 February 1742   20 years, 315 days       1727
2      3 April 1721  11 February 1742   20 years, 315 days       1734
3      3 April 1721  11 February 1742   20 years, 315 days       1741
4  16 February 1742       2 July 1743  1 year, 137 days[c]          —

          Ministerial offices held as prime minister Party         Government  \
          Ministerial offices held as prime minister Party         Government
0  Chancellor of the ExchequerFirst Lord of the T...  Whig  Walpole–Townshend
1  Chancellor of the ExchequerFirst Lord of the T...  Whig  Walpole–Townshend
2  Chancellor of the ExchequerFirst Lord of the T...  Whig            Walpole
3  Chancellor of the ExchequerFirst Lord of the T...  Whig            Walpole
4                         First Lord of the Treasury  Whig           Carteret

            MonarchReign
            MonarchReign
0   George Ir. 1714–1727
1  George IIr. 1727–1760
2  George IIr. 1727–1760
3  George IIr. 1727–1760
4  George IIr. 1727–1760

In [30]:
for i, t in enumerate(tables):
    print(f"\n=== Table {i} ===")
    print(t.shape)
    print(t.iloc[0])

=== Table 0 ===
(126, 11)
Portrait                                    Portrait                                                                                      ​
                                            Portrait.1                                                                                  NaN
Prime ministerOffice(lifespan)              Prime ministerOffice(lifespan)                Robert Walpole[26]MP for King's Lynn (to 1742)...
Term of office                              Start                                                                              3 April 1721
                                            End                                                                            11 February 1742
                                            Duration                                                                     20 years, 315 days
Mandate[a]                                  Mandate[a]                                                                                 1722
Ministerial offices held as prime minister  Ministerial offices held as prime minister    Chancellor of the ExchequerFirst Lord of the T...
Party                                       Party                                                                                      Whig
Government                                  Government                                                                    Walpole–Townshend
MonarchReign                                MonarchReign                                                               George Ir. 1714–1727
Name: 0, dtype: str

=== Table 1 ===
(2, 11)
Portrait                                    Portrait                                                                                 ​
                                            Portrait.1                                                                             NaN
Prime ministerOffice(lifespan)              Prime ministerOffice(lifespan)                William Pulteney 1st Earl of Bath(1684–1764)
Term of office                              Start                                                                     10 February 1746
                                            End                                                                       12 February 1746
                                            Duration                                                                            3 days
Mandate[a]                                  Mandate[a]                                                                               –
Ministerial offices held as prime minister  Ministerial offices held as prime minister                      First Lord of the Treasury
Party                                       Party                                                                                 Whig
Government                                  Government                                                                     Short-lived
MonarchReign                                MonarchReign                                                         George IIr. 1727–1760
Name: 0, dtype: object

=== Table 2 ===
(5, 2)
vteLists related to prime ministers of the United Kingdom      List of prime ministers
vteLists related to prime ministers of the United Kingdom.1    List of prime ministers
Name: 0, dtype: str

=== Table 3 ===
(1, 2)
0                                           By monarch
1    Victoria Edward VII George V Edward VIII Georg...
Name: 0, dtype: str

In [31]:
df_pm = tables[0].copy()

# Extract just the columns we need using tuple keys
df_pm = df_pm[[
    ('Prime ministerOffice(lifespan)', 'Prime ministerOffice(lifespan)'),
    ('Term of office', 'Start'),
    ('Term of office', 'End'),
    ('Party', 'Party')
]]

# Flatten column names
df_pm.columns = ['pm_raw', 'start', 'end', 'party']

# Parse dates
df_pm['start'] = pd.to_datetime(df_pm['start'], dayfirst=True, errors='coerce')
df_pm['end'] = pd.to_datetime(df_pm['end'], dayfirst=True, errors='coerce')

# Filter to 1910 onwards
df_pm = df_pm[df_pm['start'] >= '1910-01-01'].reset_index(drop=True)

print(df_pm)

                                               pm_raw      start        end  \
0   David Lloyd George[73]MP for Carnarvon Borough... 1916-12-06 1922-10-19
1   David Lloyd George[73]MP for Carnarvon Borough... 1916-12-06 1922-10-19
2      Bonar Law[74]MP for Glasgow Central(1858–1923) 1922-10-23 1923-05-20
3        Stanley Baldwin[75]MP for Bewdley(1867–1947) 1923-05-22 1924-01-22
4      Ramsay MacDonald[76]MP for Aberavon(1866–1937) 1924-01-22 1924-11-04
5        Stanley Baldwin[77]MP for Bewdley(1867–1947) 1924-11-04 1929-06-04
6        Ramsay MacDonald[78]MP for Seaham(1866–1937) 1929-06-05 1935-06-07
7        Ramsay MacDonald[78]MP for Seaham(1866–1937) 1929-06-05 1935-06-07
8        Ramsay MacDonald[78]MP for Seaham(1866–1937) 1929-06-05 1935-06-07
9        Stanley Baldwin[79]MP for Bewdley(1867–1947) 1935-06-07 1937-05-28
10       Stanley Baldwin[79]MP for Bewdley(1867–1947) 1935-06-07 1937-05-28
11       Stanley Baldwin[79]MP for Bewdley(1867–1947) 1935-06-07 1937-05-28
12  Neville Chamberlain[80]MP for Birmingham Edgba... 1937-05-28 1940-05-10
13  Neville Chamberlain[80]MP for Birmingham Edgba... 1937-05-28 1940-05-10
14      Winston Churchill[81]MP for Epping(1874–1965) 1940-05-10 1945-07-26
15      Winston Churchill[81]MP for Epping(1874–1965) 1940-05-10 1945-07-26
16      Clement Attlee[82]MP for Limehouse(1883–1967) 1945-07-26 1951-10-26
17      Clement Attlee[82]MP for Limehouse(1883–1967) 1945-07-26 1951-10-26
18    Winston Churchill[83]MP for Woodford(1874–1965) 1951-10-26 1955-04-05
19    Winston Churchill[83]MP for Woodford(1874–1965) 1951-10-26 1955-04-05
20  Anthony Eden[84]MP for Warwick and Leamington(... 1955-04-06 1957-01-09
21      Harold Macmillan[85]MP for Bromley(1894–1986) 1957-01-10 1963-10-18
22      Harold Macmillan[85]MP for Bromley(1894–1986) 1957-01-10 1963-10-18
23  Alec Douglas-Home[86]14th Earl of Home (to 196... 1963-10-19 1964-10-16
24  Harold Wilson[87]MP for Huyton(1916–1995)Premi... 1964-10-16 1970-06-19
25  Harold Wilson[87]MP for Huyton(1916–1995)Premi... 1964-10-16 1970-06-19
26           Edward Heath[88]MP for Bexley(1916–2005) 1970-06-19 1974-03-04
27  Harold Wilson[87]MP for Huyton(1916–1995)Premi... 1974-03-04 1976-04-05
28  Harold Wilson[87]MP for Huyton(1916–1995)Premi... 1974-03-04 1976-04-05
29  James Callaghan[89]MP for Cardiff South East(1... 1976-04-05 1979-05-04
30  Margaret Thatcher[90]MP for Finchley(1925–2013... 1979-05-04 1990-11-28
31  Margaret Thatcher[90]MP for Finchley(1925–2013... 1979-05-04 1990-11-28
32  Margaret Thatcher[90]MP for Finchley(1925–2013... 1979-05-04 1990-11-28
33  John Major[91]MP for Huntingdon(born 1943)Prem... 1990-11-28 1997-05-02
34  John Major[91]MP for Huntingdon(born 1943)Prem... 1990-11-28 1997-05-02
35  Tony Blair[92]MP for Sedgefield(born 1953)Prem... 1997-05-02 2007-06-27
36  Tony Blair[92]MP for Sedgefield(born 1953)Prem... 1997-05-02 2007-06-27
37  Tony Blair[92]MP for Sedgefield(born 1953)Prem... 1997-05-02 2007-06-27
38  Gordon Brown[93]MP for Kirkcaldy and Cowdenbea... 2007-06-27 2010-05-11
39  David Cameron[94]MP for Witney(born 1966)Premi... 2010-05-11 2016-07-13
40  David Cameron[94]MP for Witney(born 1966)Premi... 2010-05-11 2016-07-13
41  Theresa May[95]MP for Maidenhead(born 1956)Pre... 2016-07-13 2019-07-24
42  Theresa May[95]MP for Maidenhead(born 1956)Pre... 2016-07-13 2019-07-24
43  Boris Johnson[96]MP for Uxbridge and South Rui... 2019-07-24 2022-09-06
44  Boris Johnson[96]MP for Uxbridge and South Rui... 2019-07-24 2022-09-06
45  Liz Truss[97]MP for South West Norfolk(born 19... 2022-09-06 2022-10-25
46  Liz Truss[97]MP for South West Norfolk(born 19... 2022-09-06 2022-10-25
47  Rishi Sunak[98]MP for Richmond (Yorks)(born 19... 2022-10-25 2024-07-05
48  Keir Starmer[99]MP for Holborn and St Pancras ... 2024-07-05        NaT
49  Keir Starmer[99]MP for Holborn and St Pancras ... 2024-07-05        NaT
50  Keir Starmer[99]MP for Holborn and St Pancras ... 2024-07-05        NaT

                                                party
0   Coalition Liberal (1916–1922) National Liberal...
1   Coalition Liberal (1916–1922) National Liberal...
2                               Conservative(Scot.U.)
3                                        Conservative
4                                              Labour
5                                        Conservative
6                                              Labour
7                                     National Labour
8                                     National Labour
9                                        Conservative
10                                       Conservative
11                                       Conservative
12                                       Conservative
13                                       Conservative
14                                       Conservative
15                                       Conservative
16                                             Labour
17                                             Labour
18                                       Conservative
19                                       Conservative
20                                       Conservative
21                                       Conservative
22                                       Conservative
23                              Conservative(Scot.U.)
24                                             Labour
25                                             Labour
26                                       Conservative
27                                             Labour
28                                             Labour
29                                             Labour
30                                       Conservative
31                                       Conservative
32                                       Conservative
33                                       Conservative
34                                       Conservative
35                                             Labour
36                                             Labour
37                                             Labour
38                                             Labour
39                                       Conservative
40                                       Conservative
41                                       Conservative
42                                       Conservative
43                                       Conservative
44                                       Conservative
45                                       Conservative
46                                       Conservative
47                                       Conservative
48                                             Labour
49                                                NaN
50                                                NaN

In [32]:
# Clean PM name
df_pm['pm'] = df_pm['pm_raw'].str.extract(r'^([^\[]+)').iloc[:, 0].str.strip()

# Clean party
df_pm['party'] = df_pm['party'].str.replace(r'\(Scot\.U\.\)', '', regex=True).str.strip()
df_pm['party'] = df_pm['party'].str.extract(r'^([^\(]+)').iloc[:, 0].str.strip()

# Deduplicate
df_pm = df_pm.drop_duplicates(subset=['start', 'end']).reset_index(drop=True)

# Format dates
df_pm['start'] = df_pm['start'].dt.strftime('%Y-%m-%d')
df_pm['end'] = df_pm['end'].dt.strftime('%Y-%m-%d')

# Keep only what we need
df_pm = df_pm[['pm', 'party', 'start', 'end']]

print(df_pm.to_string())

                     pm              party       start         end
0    David Lloyd George  Coalition Liberal  1916-12-06  1922-10-19
1             Bonar Law       Conservative  1922-10-23  1923-05-20
2       Stanley Baldwin       Conservative  1923-05-22  1924-01-22
3      Ramsay MacDonald             Labour  1924-01-22  1924-11-04
4       Stanley Baldwin       Conservative  1924-11-04  1929-06-04
5      Ramsay MacDonald             Labour  1929-06-05  1935-06-07
6       Stanley Baldwin       Conservative  1935-06-07  1937-05-28
7   Neville Chamberlain       Conservative  1937-05-28  1940-05-10
8     Winston Churchill       Conservative  1940-05-10  1945-07-26
9        Clement Attlee             Labour  1945-07-26  1951-10-26
10    Winston Churchill       Conservative  1951-10-26  1955-04-05
11         Anthony Eden       Conservative  1955-04-06  1957-01-09
12     Harold Macmillan       Conservative  1957-01-10  1963-10-18
13    Alec Douglas-Home       Conservative  1963-10-19  1964-10-16
14        Harold Wilson             Labour  1964-10-16  1970-06-19
15         Edward Heath       Conservative  1970-06-19  1974-03-04
16        Harold Wilson             Labour  1974-03-04  1976-04-05
17      James Callaghan             Labour  1976-04-05  1979-05-04
18    Margaret Thatcher       Conservative  1979-05-04  1990-11-28
19           John Major       Conservative  1990-11-28  1997-05-02
20           Tony Blair             Labour  1997-05-02  2007-06-27
21         Gordon Brown             Labour  2007-06-27  2010-05-11
22        David Cameron       Conservative  2010-05-11  2016-07-13
23          Theresa May       Conservative  2016-07-13  2019-07-24
24        Boris Johnson       Conservative  2019-07-24  2022-09-06
25            Liz Truss       Conservative  2022-09-06  2022-10-25
26          Rishi Sunak       Conservative  2022-10-25  2024-07-05
27         Keir Starmer             Labour  2024-07-05         NaN

In [33]:
# Add Asquith
asquith = pd.DataFrame([{
    'pm': 'H. H. Asquith',
    'party': 'Liberal',
    'start': '1910-12-19',
    'end': '1916-12-06'
}])

# Split MacDonald 1929-1935 into two entries
# Remove the single 1929-1935 entry
df_pm = df_pm[~((df_pm['pm'] == 'Ramsay MacDonald') & (df_pm['start'] == '1929-06-05'))]

# Add the two correct entries
macdonald_labour = pd.DataFrame([{
    'pm': 'Ramsay MacDonald',
    'party': 'Labour',
    'start': '1929-06-05',
    'end': '1931-08-24'
}])

macdonald_national = pd.DataFrame([{
    'pm': 'Ramsay MacDonald',
    'party': 'National Labour',
    'start': '1931-08-24',
    'end': '1935-06-07'
}])

# Combine and sort
df_pm = pd.concat([asquith, df_pm, macdonald_labour, macdonald_national], ignore_index=True)
df_pm = df_pm.sort_values('start').reset_index(drop=True)

print(df_pm.to_string())

                     pm              party       start         end
0         H. H. Asquith            Liberal  1910-12-19  1916-12-06
1    David Lloyd George  Coalition Liberal  1916-12-06  1922-10-19
2             Bonar Law       Conservative  1922-10-23  1923-05-20
3       Stanley Baldwin       Conservative  1923-05-22  1924-01-22
4      Ramsay MacDonald             Labour  1924-01-22  1924-11-04
5       Stanley Baldwin       Conservative  1924-11-04  1929-06-04
6      Ramsay MacDonald             Labour  1929-06-05  1931-08-24
7      Ramsay MacDonald    National Labour  1931-08-24  1935-06-07
8       Stanley Baldwin       Conservative  1935-06-07  1937-05-28
9   Neville Chamberlain       Conservative  1937-05-28  1940-05-10
10    Winston Churchill       Conservative  1940-05-10  1945-07-26
11       Clement Attlee             Labour  1945-07-26  1951-10-26
12    Winston Churchill       Conservative  1951-10-26  1955-04-05
13         Anthony Eden       Conservative  1955-04-06  1957-01-09
14     Harold Macmillan       Conservative  1957-01-10  1963-10-18
15    Alec Douglas-Home       Conservative  1963-10-19  1964-10-16
16        Harold Wilson             Labour  1964-10-16  1970-06-19
17         Edward Heath       Conservative  1970-06-19  1974-03-04
18        Harold Wilson             Labour  1974-03-04  1976-04-05
19      James Callaghan             Labour  1976-04-05  1979-05-04
20    Margaret Thatcher       Conservative  1979-05-04  1990-11-28
21           John Major       Conservative  1990-11-28  1997-05-02
22           Tony Blair             Labour  1997-05-02  2007-06-27
23         Gordon Brown             Labour  2007-06-27  2010-05-11
24        David Cameron       Conservative  2010-05-11  2016-07-13
25          Theresa May       Conservative  2016-07-13  2019-07-24
26        Boris Johnson       Conservative  2019-07-24  2022-09-06
27            Liz Truss       Conservative  2022-09-06  2022-10-25
28          Rishi Sunak       Conservative  2022-10-25  2024-07-05
29         Keir Starmer             Labour  2024-07-05         NaN

## Building the timeline table

In [48]:
print(election_df.columns)
print(df_pm.columns)
print(df_timeline.columns)

Index(['election_date', 'total_seats', 'con_votes', 'con_seats', 'lab_votes',
       'lab_seats', 'lib_votes', 'lib_seats', 'oth_votes', 'oth_seats',
       'comment'],
      dtype='str')
Index(['pm', 'party', 'start', 'end'], dtype='str')
Index(['pm', 'party', 'pm_start_date', 'pm_end_date', 'election_date',
       'own_mandate', 'seats_won', 'total_seats', 'majority', 'majority_end',
       'opposition_party', 'coalition_parties', 'resignation_date',
       'end_reason', 'resignation', 'notes'],
      dtype='str')

In [54]:
# Start fresh from df_pm
df_timeline = df_pm.copy().rename(columns={'start': 'pm_start_date', 'end': 'pm_end_date'})
print(display(df_timeline))

                     pm              party pm_start_date pm_end_date
0         H. H. Asquith            Liberal    1910-12-19  1916-12-06
1    David Lloyd George  Coalition Liberal    1916-12-06  1922-10-19
2             Bonar Law       Conservative    1922-10-23  1923-05-20
3       Stanley Baldwin       Conservative    1923-05-22  1924-01-22
4      Ramsay MacDonald             Labour    1924-01-22  1924-11-04
5       Stanley Baldwin       Conservative    1924-11-04  1929-06-04
6      Ramsay MacDonald             Labour    1929-06-05  1931-08-24
7      Ramsay MacDonald    National Labour    1931-08-24  1935-06-07
8       Stanley Baldwin       Conservative    1935-06-07  1937-05-28
9   Neville Chamberlain       Conservative    1937-05-28  1940-05-10
10    Winston Churchill       Conservative    1940-05-10  1945-07-26
11       Clement Attlee             Labour    1945-07-26  1951-10-26
12    Winston Churchill       Conservative    1951-10-26  1955-04-05
13         Anthony Eden       Conservative    1955-04-06  1957-01-09
14     Harold Macmillan       Conservative    1957-01-10  1963-10-18
15    Alec Douglas-Home       Conservative    1963-10-19  1964-10-16
16        Harold Wilson             Labour    1964-10-16  1970-06-19
17         Edward Heath       Conservative    1970-06-19  1974-03-04
18        Harold Wilson             Labour    1974-03-04  1976-04-05
19      James Callaghan             Labour    1976-04-05  1979-05-04
20    Margaret Thatcher       Conservative    1979-05-04  1990-11-28
21           John Major       Conservative    1990-11-28  1997-05-02
22           Tony Blair             Labour    1997-05-02  2007-06-27
23         Gordon Brown             Labour    2007-06-27  2010-05-11
24        David Cameron       Conservative    2010-05-11  2016-07-13
25          Theresa May       Conservative    2016-07-13  2019-07-24
26        Boris Johnson       Conservative    2019-07-24  2022-09-06
27            Liz Truss       Conservative    2022-09-06  2022-10-25
28          Rishi Sunak       Conservative    2022-10-25  2024-07-05
29         Keir Starmer             Labour    2024-07-05         NaN

None

In [55]:
print(election_df[['election_date', 'con_seats', 'lab_seats', 'lib_seats', 'oth_seats', 'total_seats', 'comment']].to_string())

   election_date  con_seats  lab_seats  lib_seats  oth_seats  total_seats                                                           comment
0     1910-12-19        272         42        272         84          670   Repeat election forced by George V to legitimise Parliament Act
1     1918-12-14        383         73        161         90          707                       Lloyd George (Lib) leads coalition with Con
2     1922-11-15        345        142        116         12          615        Bonar Law (Con) breaks the coalition, Labour overtakes Lib
3     1923-12-06        258        191        159          7          615     Ramsay MacDonald (Lab) with Lib-coalition beats Baldwin (Con)
4     1924-10-29        419        151         40          5          615       Baldwin (Con) elected after Liberals bring down Labour govt
5     1929-05-30        260        288         59          8          615             Ramsay MacDonald (Lab) minority govt with Lib support
6     1931-10-27        521         52         37          5          615         National Govt (Con plus some Lib and Lab) under MacDonald
7     1935-11-14        432        154         20          9          615                     National Govt led by Baldwin (Con) re-elected
8     1945-07-05        213        393         12         22          640           Attlee (Lab) beats Churchill (Con) in post-war election
9     1950-02-23        298        315          9          3          625                       Attlee (Lab) beats Churchill (Con) narrowly
10    1951-10-25        321        295          6          3          625        Churchill (Con) beats Attlee (Lab) after economic problems
11    1955-05-26        345        277          6          2          630                         Eden (Con) beats Attlee (Lab) comfortably
12    1959-10-08        365        258          6          1          630         Macmillan (Con) beats Gaitskell (Lab) with strong economy
13    1964-10-15        304        317          9          0          630      Wilson (Lab) narrowly beats Douglas-Home (Con) after Profumo
14    1966-03-31        253        364         12          1          630               Wilson (Lab) beats Heath (Con) with strong majority
15    1970-06-18        330        288          6          6          630          Heath (Con) beats Wilson (Lab), surprising the pollsters
16    1974-02-28        297        301         14         23          635              Wilson (Lab) minority govt after industrial disputes
17    1974-10-10        277        319         13         26          635                Repeat election gives Wilson (Lab) a tiny majority
18    1979-05-03        339        269         11         16          635      Thatcher (Con) beats Callaghan (Lab) after industrial unrest
19    1983-06-09        397        209         23         21          650       Thatcher (Con) landslide over Foot (Lab) after Labour split
20    1987-06-11        376        229         22         23          650  Thatcher (Con) landslide over Kinnock (Lab) and Lib/SDP alliance
21    1992-04-09        336        271         20         24          651                     Major (Con) narrow victory over Kinnock (Lab)
22    1997-05-01        165        419         46         29          659                            Blair (Lab) landslide over Major (Con)
23    2001-06-07        166        413         52         28          659                            Blair (Lab) landslide over Hague (Con)
24    2005-05-05        198        356         62         30          646             Blair (Lab) beats Howard (Con), with reduced majority
25    2010-05-06        307        258         57         28          650                       Cameron (Con) leads coalition with Lib Dems
26    2015-05-07        331        232          8         79          650         Cameron (Con) beats Miliband (Lab) to get a slim majority
27    2017-06-08        318        262         12         58          650                       May (Con) minority govt after EU Referendum
28    2019-12-12        365        203         11         71          650             Johnson (Con) beats Corbyn (Lab) with strong majority
29    2024-07-04        121        412         72         45          650                          Starmer (Lab) landslide over Sunak (Con)

In [58]:
# Add all missing columns
for col in ['election_date', 'own_mandate', 'seats_won', 'total_seats', 
            'majority', 'majority_end', 'opposition_party', 'coalition_parties', 
            'resignation_date', 'end_reason', 'resignation', 'notes']:
    df_timeline[col] = None

election_df['election_date'] = pd.to_datetime(election_df['election_date']).dt.strftime('%Y-%m-%d')


# Then export both
df_timeline.to_excel('pm_timeline_working.xlsx', index=False)
election_df.to_excel('election_data.xlsx', index=False)

In [59]:
print(df_timeline[df_timeline['pm'] == 'Ramsay MacDonald'].to_string())

                 pm            party pm_start_date pm_end_date election_date own_mandate seats_won total_seats majority majority_end opposition_party coalition_parties resignation_date end_reason resignation notes
4  Ramsay MacDonald           Labour    1924-01-22  1924-11-04          None        None      None        None     None         None             None              None             None       None        None  None
6  Ramsay MacDonald           Labour    1929-06-05  1931-08-24          None        None      None        None     None         None             None              None             None       None        None  None
7  Ramsay MacDonald  National Labour    1931-08-24  1935-06-07          None        None      None        None     None         None             None              None             None       None        None  None

## Collected Data and Filled in the table in excel

## Reading the table back into pandas

In [62]:
df_timeline = pd.read_excel('pm_timeline_working.xlsx')
print(df_timeline.columns.tolist())
print(df_timeline.shape)
display(df_timeline)

['pm', 'party', 'pm_start_date', 'pm_end_date', 'election_date', 'own_mandate', 'seats_won', 'total_seats', 'opposition_party', 'majority', 'coalition_parties', 'end_reason', 'notes']
(48, 13)

,pm,party,pm_start_date,pm_end_date,election_date,own_mandate,seats_won,total_seats,opposition_party,majority,coalition_parties,end_reason,notes
0,H. H. Asquith,Liberal,1910-12-19,1916-12-06,1910-12-19,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
1,David Lloyd George,Coalition Liberal,1916-12-06,1918-12-14,1910-12-19,False,NaN,NaN,Liberal,NaN,"Conservative, Labour",NaN,NaN
2,David Lloyd George,Coalition Liberal,1918-12-14,1922-10-19,1918-12-14,True,521.0,NaN,Liberal,NaN,"Conservative, National Liberal",NaN,NaN
3,Bonar Law,Conservative,1922-10-23,1922-11-15,1918-12-14,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
4,Bonar Law,Conservative,1922-11-15,1923-05-20,1922-11-15,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
5,Stanley Baldwin,Conservative,1923-05-22,1923-12-06,1922-11-15,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
6,Stanley Baldwin,Conservative,1923-12-06,1924-01-22,1923-12-06,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
7,Ramsay MacDonald,Labour,1924-01-22,1924-11-04,1923-12-06,False,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
8,Stanley Baldwin,Conservative,1924-11-04,1929-06-04,1924-10-29,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
9,Ramsay MacDonald,Labour,1929-06-05,1931-08-24 00:00:00,1929-05-30,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
10,Ramsay MacDonald,National Labour,1931-08-24 00:00:00,1931-10-27,1929-05-30,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
11,Ramsay MacDonald,National Labour,1931-10-27,1935-06-07,1931-10-27,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
12,Stanley Baldwin,Conservative,1935-06-07,1935-11-14,1931-10-27,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
13,Stanley Baldwin,Conservative,1935-11-14,1937-05-28,1935-11-14,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
14,Neville Chamberlain,Conservative,1937-05-28,1940-05-10,1935-11-14,False,429.0,NaN,Labour,NaN,"National Labour, Liberal National",NaN,NaN
15,Winston Churchill,Conservative,1940-05-10,1945-07-26,1935-11-14,False,429.0,NaN,NaN,NaN,"Labour, Liberal National, Liberal, National La...",NaN,NaN
16,Clement Attlee,Labour,1945-07-26,1950-02-23,1945-07-05,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
17,Clement Attlee,Labour,1950-02-23,1951-10-26,1950-02-23,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
18,Winston Churchill,Conservative,1951-10-26,1955-04-05,1951-10-25,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
19,Anthony Eden,Conservative,1955-04-06,1955-05-26,1951-10-25,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
20,Anthony Eden,Conservative,1955-05-26,1957-01-09,1955-05-26,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
21,Harold Macmillan,Conservative,1957-01-10,1959-10-08,1955-05-26,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
22,Harold Macmillan,Conservative,1959-10-08,1963-10-18,1959-10-08,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
23,Alec Douglas-Home,Conservative,1963-10-19,1964-10-16,1959-10-08,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
24,Harold Wilson,Labour,1964-10-16,1966-03-31,1964-10-15,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
25,Harold Wilson,Labour,1966-03-31,1970-06-19,1966-03-31,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
26,Edward Heath,Conservative,1970-06-19,1974-03-04,1970-06-18,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
27,Harold Wilson,Labour,1974-03-04,1974-10-10,1974-02-28,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
28,Harold Wilson,Labour,1974-10-10,1976-04-05,1974-10-10,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
29,James Callaghan,Labour,1976-04-05,1979-05-04,1974-10-10,False,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
30,Margaret Thatcher,Conservative,1979-05-04,1983-06-09,1979-05-03,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
31,Margaret Thatcher,Conservative,1983-06-09,1987-06-11,1983-06-09,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
32,Margaret Thatcher,Conservative,1987-06-11,1990-11-28,1987-06-11,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
33,John Major,Conservative,1990-11-28,1992-04-09,1987-06-11,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
34,John Major,Conservative,1992-04-09,1997-05-02,1992-04-09,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
35,Tony Blair,Labour,1997-05-02,2001-06-07,1997-05-01,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
36,Tony Blair,Labour,2001-06-07,2005-05-05,2001-06-07,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
37,Tony Blair,Labour,2005-05-05,2007-06-27,2005-05-05,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
38,Gordon Brown,Labour,2007-06-27,2010-05-11,2005-05-05,False,NaN,NaN,Conservative,NaN,NaN,NaN,NaN
39,David Cameron,Conservative,2010-05-11,2015-05-07,2010-05-06,True,363.0,NaN,Labour,NaN,Liberal Democrats,NaN,NaN
40,David Cameron,Conservative,2015-05-07,2016-07-13,2015-05-07,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
41,Theresa May,Conservative,2016-07-13,2017-06-08,2015-05-07,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
42,Theresa May,Conservative,2017-06-08,2019-07-24,2017-06-08,True,NaN,NaN,Labour,NaN,Democratic Unionist Party,NaN,NaN
43,Boris Johnson,Conservative,2019-07-24,2019-12-12,2017-06-08,False,NaN,NaN,Labour,NaN,Democratic Unionist Party,NaN,NaN
44,Boris Johnson,Conservative,2019-12-12,2022-09-06,2019-12-12,True,NaN,NaN,Labour,NaN,NaN,NaN,NaN
45,Liz Truss,Conservative,2022-09-06,2022-10-25,2019-12-12,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
46,Rishi Sunak,Conservative,2022-10-25,2024-07-05,2019-12-12,False,NaN,NaN,Labour,NaN,NaN,NaN,NaN
47,Keir Starmer,Labour,2024-07-05,NaN,2024-07-04,True,NaN,NaN,Conservative,NaN,NaN,NaN,NaN

In [ ]:
for col in ['pm_start_date', 'pm_end_date', 'election_date']:
    df_timeline[col] = pd.to_datetime(df_timeline[col]).dt.strftime('%Y-%m-%d')
display(df_timeline)

In [65]:
# Strip times from election_df election_date first
election_df['election_date'] = pd.to_datetime(election_df['election_date']).dt.strftime('%Y-%m-%d')

# Fill in total_seats from election_df where it's missing
df_timeline['total_seats'] = df_timeline['total_seats'].fillna(
    df_timeline['election_date'].map(election_df.set_index('election_date')['total_seats'])
)

print(df_timeline[['pm', 'election_date', 'total_seats']].to_string())
display(df_timeline)

                     pm election_date  total_seats
0         H. H. Asquith    1910-12-19        670.0
1    David Lloyd George    1910-12-19        670.0
2    David Lloyd George    1918-12-14        707.0
3             Bonar Law    1918-12-14        707.0
4             Bonar Law    1922-11-15        615.0
5       Stanley Baldwin    1922-11-15        615.0
6       Stanley Baldwin    1923-12-06        615.0
7      Ramsay MacDonald    1923-12-06        615.0
8       Stanley Baldwin    1924-10-29        615.0
9      Ramsay MacDonald    1929-05-30        615.0
10     Ramsay MacDonald    1929-05-30        615.0
11     Ramsay MacDonald    1931-10-27        615.0
12      Stanley Baldwin    1931-10-27        615.0
13      Stanley Baldwin    1935-11-14        615.0
14  Neville Chamberlain    1935-11-14        615.0
15    Winston Churchill    1935-11-14        615.0
16       Clement Attlee    1945-07-05        640.0
17       Clement Attlee    1950-02-23        625.0
18    Winston Churchill    1951-10-25        625.0
19         Anthony Eden    1951-10-25        625.0
20         Anthony Eden    1955-05-26        630.0
21     Harold Macmillan    1955-05-26        630.0
22     Harold Macmillan    1959-10-08        630.0
23    Alec Douglas-Home    1959-10-08        630.0
24        Harold Wilson    1964-10-15        630.0
25        Harold Wilson    1966-03-31        630.0
26         Edward Heath    1970-06-18        630.0
27        Harold Wilson    1974-02-28        635.0
28        Harold Wilson    1974-10-10        635.0
29      James Callaghan    1974-10-10        635.0
30    Margaret Thatcher    1979-05-03        635.0
31    Margaret Thatcher    1983-06-09        650.0
32    Margaret Thatcher    1987-06-11        650.0
33           John Major    1987-06-11        650.0
34           John Major    1992-04-09        651.0
35           Tony Blair    1997-05-01        659.0
36           Tony Blair    2001-06-07        659.0
37           Tony Blair    2005-05-05        646.0
38         Gordon Brown    2005-05-05        646.0
39        David Cameron    2010-05-06        650.0
40        David Cameron    2015-05-07        650.0
41          Theresa May    2015-05-07        650.0
42          Theresa May    2017-06-08        650.0
43        Boris Johnson    2017-06-08        650.0
44        Boris Johnson    2019-12-12        650.0
45            Liz Truss    2019-12-12        650.0
46          Rishi Sunak    2019-12-12        650.0
47         Keir Starmer    2024-07-04        650.0

,pm,party,pm_start_date,pm_end_date,election_date,own_mandate,seats_won,total_seats,opposition_party,majority,coalition_parties,end_reason,notes
0,H. H. Asquith,Liberal,1910-12-19,1916-12-06,1910-12-19,True,NaN,670.0,Conservative,NaN,NaN,NaN,NaN
1,David Lloyd George,Coalition Liberal,1916-12-06,1918-12-14,1910-12-19,False,NaN,670.0,Liberal,NaN,"Conservative, Labour",NaN,NaN
2,David Lloyd George,Coalition Liberal,1918-12-14,1922-10-19,1918-12-14,True,521.0,707.0,Liberal,NaN,"Conservative, National Liberal",NaN,NaN
3,Bonar Law,Conservative,1922-10-23,1922-11-15,1918-12-14,False,NaN,707.0,Labour,NaN,NaN,NaN,NaN
4,Bonar Law,Conservative,1922-11-15,1923-05-20,1922-11-15,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
5,Stanley Baldwin,Conservative,1923-05-22,1923-12-06,1922-11-15,False,NaN,615.0,Labour,NaN,NaN,NaN,NaN
6,Stanley Baldwin,Conservative,1923-12-06,1924-01-22,1923-12-06,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
7,Ramsay MacDonald,Labour,1924-01-22,1924-11-04,1923-12-06,False,NaN,615.0,Conservative,NaN,NaN,NaN,NaN
8,Stanley Baldwin,Conservative,1924-11-04,1929-06-04,1924-10-29,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
9,Ramsay MacDonald,Labour,1929-06-05,1931-08-24,1929-05-30,True,NaN,615.0,Conservative,NaN,NaN,NaN,NaN
10,Ramsay MacDonald,National Labour,1931-08-24,1931-10-27,1929-05-30,False,NaN,615.0,Labour,NaN,NaN,NaN,NaN
11,Ramsay MacDonald,National Labour,1931-10-27,1935-06-07,1931-10-27,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
12,Stanley Baldwin,Conservative,1935-06-07,1935-11-14,1931-10-27,False,NaN,615.0,Labour,NaN,NaN,NaN,NaN
13,Stanley Baldwin,Conservative,1935-11-14,1937-05-28,1935-11-14,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
14,Neville Chamberlain,Conservative,1937-05-28,1940-05-10,1935-11-14,False,429.0,615.0,Labour,NaN,"National Labour, Liberal National",NaN,NaN
15,Winston Churchill,Conservative,1940-05-10,1945-07-26,1935-11-14,False,429.0,615.0,NaN,NaN,"Labour, Liberal National, Liberal, National La...",NaN,NaN
16,Clement Attlee,Labour,1945-07-26,1950-02-23,1945-07-05,True,NaN,640.0,Conservative,NaN,NaN,NaN,NaN
17,Clement Attlee,Labour,1950-02-23,1951-10-26,1950-02-23,True,NaN,625.0,Conservative,NaN,NaN,NaN,NaN
18,Winston Churchill,Conservative,1951-10-26,1955-04-05,1951-10-25,True,NaN,625.0,Labour,NaN,NaN,NaN,NaN
19,Anthony Eden,Conservative,1955-04-06,1955-05-26,1951-10-25,False,NaN,625.0,Labour,NaN,NaN,NaN,NaN
20,Anthony Eden,Conservative,1955-05-26,1957-01-09,1955-05-26,True,NaN,630.0,Labour,NaN,NaN,NaN,NaN
21,Harold Macmillan,Conservative,1957-01-10,1959-10-08,1955-05-26,False,NaN,630.0,Labour,NaN,NaN,NaN,NaN
22,Harold Macmillan,Conservative,1959-10-08,1963-10-18,1959-10-08,True,NaN,630.0,Labour,NaN,NaN,NaN,NaN
23,Alec Douglas-Home,Conservative,1963-10-19,1964-10-16,1959-10-08,False,NaN,630.0,Labour,NaN,NaN,NaN,NaN
24,Harold Wilson,Labour,1964-10-16,1966-03-31,1964-10-15,True,NaN,630.0,Conservative,NaN,NaN,NaN,NaN
25,Harold Wilson,Labour,1966-03-31,1970-06-19,1966-03-31,True,NaN,630.0,Conservative,NaN,NaN,NaN,NaN
26,Edward Heath,Conservative,1970-06-19,1974-03-04,1970-06-18,True,NaN,630.0,Labour,NaN,NaN,NaN,NaN
27,Harold Wilson,Labour,1974-03-04,1974-10-10,1974-02-28,True,NaN,635.0,Conservative,NaN,NaN,NaN,NaN
28,Harold Wilson,Labour,1974-10-10,1976-04-05,1974-10-10,True,NaN,635.0,Conservative,NaN,NaN,NaN,NaN
29,James Callaghan,Labour,1976-04-05,1979-05-04,1974-10-10,False,NaN,635.0,Conservative,NaN,NaN,NaN,NaN
30,Margaret Thatcher,Conservative,1979-05-04,1983-06-09,1979-05-03,True,NaN,635.0,Labour,NaN,NaN,NaN,NaN
31,Margaret Thatcher,Conservative,1983-06-09,1987-06-11,1983-06-09,True,NaN,650.0,Labour,NaN,NaN,NaN,NaN
32,Margaret Thatcher,Conservative,1987-06-11,1990-11-28,1987-06-11,True,NaN,650.0,Labour,NaN,NaN,NaN,NaN
33,John Major,Conservative,1990-11-28,1992-04-09,1987-06-11,False,NaN,650.0,Labour,NaN,NaN,NaN,NaN
34,John Major,Conservative,1992-04-09,1997-05-02,1992-04-09,True,NaN,651.0,Labour,NaN,NaN,NaN,NaN
35,Tony Blair,Labour,1997-05-02,2001-06-07,1997-05-01,True,NaN,659.0,Conservative,NaN,NaN,NaN,NaN
36,Tony Blair,Labour,2001-06-07,2005-05-05,2001-06-07,True,NaN,659.0,Conservative,NaN,NaN,NaN,NaN
37,Tony Blair,Labour,2005-05-05,2007-06-27,2005-05-05,True,NaN,646.0,Conservative,NaN,NaN,NaN,NaN
38,Gordon Brown,Labour,2007-06-27,2010-05-11,2005-05-05,False,NaN,646.0,Conservative,NaN,NaN,NaN,NaN
39,David Cameron,Conservative,2010-05-11,2015-05-07,2010-05-06,True,363.0,650.0,Labour,NaN,Liberal Democrats,NaN,NaN
40,David Cameron,Conservative,2015-05-07,2016-07-13,2015-05-07,True,NaN,650.0,Labour,NaN,NaN,NaN,NaN
41,Theresa May,Conservative,2016-07-13,2017-06-08,2015-05-07,False,NaN,650.0,Labour,NaN,NaN,NaN,NaN
42,Theresa May,Conservative,2017-06-08,2019-07-24,2017-06-08,True,NaN,650.0,Labour,NaN,Democratic Unionist Party,NaN,NaN
43,Boris Johnson,Conservative,2019-07-24,2019-12-12,2017-06-08,False,NaN,650.0,Labour,NaN,Democratic Unionist Party,NaN,NaN
44,Boris Johnson,Conservative,2019-12-12,2022-09-06,2019-12-12,True,NaN,650.0,Labour,NaN,NaN,NaN,NaN
45,Liz Truss,Conservative,2022-09-06,2022-10-25,2019-12-12,False,NaN,650.0,Labour,NaN,NaN,NaN,NaN
46,Rishi Sunak,Conservative,2022-10-25,2024-07-05,2019-12-12,False,NaN,650.0,Labour,NaN,NaN,NaN,NaN
47,Keir Starmer,Labour,2024-07-05,NaN,2024-07-04,True,NaN,650.0,Conservative,NaN,NaN,NaN,NaN

In [ ]:
# Create a mapping of election_date to seats by party
con_seats = election_df.set_index('election_date')['con_seats']
lab_seats = election_df.set_index('election_date')['lab_seats']

# Fill in seats_won where missing based on party
def fill_seats(row):
    if pd.notna(row['seats_won']):
        return row['seats_won']
    if row['party'] == 'Conservative':
        return con_seats.get(row['election_date'])
    elif row['party'] == 'Labour':
        return lab_seats.get(row['election_date'])
    return None

df_timeline['seats_won'] = df_timeline.apply(fill_seats, axis=1)

# print(df_timeline[['pm', 'party', 'election_date', 'seats_won']].to_string())
display(df_timeline)

                     pm              party election_date  seats_won
0         H. H. Asquith            Liberal    1910-12-19        NaN
1    David Lloyd George  Coalition Liberal    1910-12-19        NaN
2    David Lloyd George  Coalition Liberal    1918-12-14      521.0
3             Bonar Law       Conservative    1918-12-14      383.0
4             Bonar Law       Conservative    1922-11-15      345.0
5       Stanley Baldwin       Conservative    1922-11-15      345.0
6       Stanley Baldwin       Conservative    1923-12-06      258.0
7      Ramsay MacDonald             Labour    1923-12-06      191.0
8       Stanley Baldwin       Conservative    1924-10-29      419.0
9      Ramsay MacDonald             Labour    1929-05-30      288.0
10     Ramsay MacDonald    National Labour    1929-05-30        NaN
11     Ramsay MacDonald    National Labour    1931-10-27        NaN
12      Stanley Baldwin       Conservative    1931-10-27      521.0
13      Stanley Baldwin       Conservative    1935-11-14      432.0
14  Neville Chamberlain       Conservative    1935-11-14      429.0
15    Winston Churchill       Conservative    1935-11-14      429.0
16       Clement Attlee             Labour    1945-07-05      393.0
17       Clement Attlee             Labour    1950-02-23      315.0
18    Winston Churchill       Conservative    1951-10-25      321.0
19         Anthony Eden       Conservative    1951-10-25      321.0
20         Anthony Eden       Conservative    1955-05-26      345.0
21     Harold Macmillan       Conservative    1955-05-26      345.0
22     Harold Macmillan       Conservative    1959-10-08      365.0
23    Alec Douglas-Home       Conservative    1959-10-08      365.0
24        Harold Wilson             Labour    1964-10-15      317.0
25        Harold Wilson             Labour    1966-03-31      364.0
26         Edward Heath       Conservative    1970-06-18      330.0
27        Harold Wilson             Labour    1974-02-28      301.0
28        Harold Wilson             Labour    1974-10-10      319.0
29      James Callaghan             Labour    1974-10-10      319.0
30    Margaret Thatcher       Conservative    1979-05-03      339.0
31    Margaret Thatcher       Conservative    1983-06-09      397.0
32    Margaret Thatcher       Conservative    1987-06-11      376.0
33           John Major       Conservative    1987-06-11      376.0
34           John Major       Conservative    1992-04-09      336.0
35           Tony Blair             Labour    1997-05-01      419.0
36           Tony Blair             Labour    2001-06-07      413.0
37           Tony Blair             Labour    2005-05-05      356.0
38         Gordon Brown             Labour    2005-05-05      356.0
39        David Cameron       Conservative    2010-05-06      363.0
40        David Cameron       Conservative    2015-05-07      331.0
41          Theresa May       Conservative    2015-05-07      331.0
42          Theresa May       Conservative    2017-06-08      318.0
43        Boris Johnson       Conservative    2017-06-08      318.0
44        Boris Johnson       Conservative    2019-12-12      365.0
45            Liz Truss       Conservative    2019-12-12      365.0
46          Rishi Sunak       Conservative    2019-12-12      365.0
47         Keir Starmer             Labour    2024-07-04      412.0

,pm,party,pm_start_date,pm_end_date,election_date,own_mandate,seats_won,total_seats,opposition_party,majority,coalition_parties,end_reason,notes
0,H. H. Asquith,Liberal,1910-12-19,1916-12-06,1910-12-19,True,NaN,670.0,Conservative,NaN,NaN,NaN,NaN
1,David Lloyd George,Coalition Liberal,1916-12-06,1918-12-14,1910-12-19,False,NaN,670.0,Liberal,NaN,"Conservative, Labour",NaN,NaN
2,David Lloyd George,Coalition Liberal,1918-12-14,1922-10-19,1918-12-14,True,521.0,707.0,Liberal,NaN,"Conservative, National Liberal",NaN,NaN
3,Bonar Law,Conservative,1922-10-23,1922-11-15,1918-12-14,False,383.0,707.0,Labour,NaN,NaN,NaN,NaN
4,Bonar Law,Conservative,1922-11-15,1923-05-20,1922-11-15,True,345.0,615.0,Labour,NaN,NaN,NaN,NaN
5,Stanley Baldwin,Conservative,1923-05-22,1923-12-06,1922-11-15,False,345.0,615.0,Labour,NaN,NaN,NaN,NaN
6,Stanley Baldwin,Conservative,1923-12-06,1924-01-22,1923-12-06,True,258.0,615.0,Labour,NaN,NaN,NaN,NaN
7,Ramsay MacDonald,Labour,1924-01-22,1924-11-04,1923-12-06,False,191.0,615.0,Conservative,NaN,NaN,NaN,NaN
8,Stanley Baldwin,Conservative,1924-11-04,1929-06-04,1924-10-29,True,419.0,615.0,Labour,NaN,NaN,NaN,NaN
9,Ramsay MacDonald,Labour,1929-06-05,1931-08-24,1929-05-30,True,288.0,615.0,Conservative,NaN,NaN,NaN,NaN
10,Ramsay MacDonald,National Labour,1931-08-24,1931-10-27,1929-05-30,False,NaN,615.0,Labour,NaN,NaN,NaN,NaN
11,Ramsay MacDonald,National Labour,1931-10-27,1935-06-07,1931-10-27,True,NaN,615.0,Labour,NaN,NaN,NaN,NaN
12,Stanley Baldwin,Conservative,1935-06-07,1935-11-14,1931-10-27,False,521.0,615.0,Labour,NaN,NaN,NaN,NaN
13,Stanley Baldwin,Conservative,1935-11-14,1937-05-28,1935-11-14,True,432.0,615.0,Labour,NaN,NaN,NaN,NaN
14,Neville Chamberlain,Conservative,1937-05-28,1940-05-10,1935-11-14,False,429.0,615.0,Labour,NaN,"National Labour, Liberal National",NaN,NaN
15,Winston Churchill,Conservative,1940-05-10,1945-07-26,1935-11-14,False,429.0,615.0,NaN,NaN,"Labour, Liberal National, Liberal, National La...",NaN,NaN
16,Clement Attlee,Labour,1945-07-26,1950-02-23,1945-07-05,True,393.0,640.0,Conservative,NaN,NaN,NaN,NaN
17,Clement Attlee,Labour,1950-02-23,1951-10-26,1950-02-23,True,315.0,625.0,Conservative,NaN,NaN,NaN,NaN
18,Winston Churchill,Conservative,1951-10-26,1955-04-05,1951-10-25,True,321.0,625.0,Labour,NaN,NaN,NaN,NaN
19,Anthony Eden,Conservative,1955-04-06,1955-05-26,1951-10-25,False,321.0,625.0,Labour,NaN,NaN,NaN,NaN
20,Anthony Eden,Conservative,1955-05-26,1957-01-09,1955-05-26,True,345.0,630.0,Labour,NaN,NaN,NaN,NaN
21,Harold Macmillan,Conservative,1957-01-10,1959-10-08,1955-05-26,False,345.0,630.0,Labour,NaN,NaN,NaN,NaN
22,Harold Macmillan,Conservative,1959-10-08,1963-10-18,1959-10-08,True,365.0,630.0,Labour,NaN,NaN,NaN,NaN
23,Alec Douglas-Home,Conservative,1963-10-19,1964-10-16,1959-10-08,False,365.0,630.0,Labour,NaN,NaN,NaN,NaN
24,Harold Wilson,Labour,1964-10-16,1966-03-31,1964-10-15,True,317.0,630.0,Conservative,NaN,NaN,NaN,NaN
25,Harold Wilson,Labour,1966-03-31,1970-06-19,1966-03-31,True,364.0,630.0,Conservative,NaN,NaN,NaN,NaN
26,Edward Heath,Conservative,1970-06-19,1974-03-04,1970-06-18,True,330.0,630.0,Labour,NaN,NaN,NaN,NaN
27,Harold Wilson,Labour,1974-03-04,1974-10-10,1974-02-28,True,301.0,635.0,Conservative,NaN,NaN,NaN,NaN
28,Harold Wilson,Labour,1974-10-10,1976-04-05,1974-10-10,True,319.0,635.0,Conservative,NaN,NaN,NaN,NaN
29,James Callaghan,Labour,1976-04-05,1979-05-04,1974-10-10,False,319.0,635.0,Conservative,NaN,NaN,NaN,NaN
30,Margaret Thatcher,Conservative,1979-05-04,1983-06-09,1979-05-03,True,339.0,635.0,Labour,NaN,NaN,NaN,NaN
31,Margaret Thatcher,Conservative,1983-06-09,1987-06-11,1983-06-09,True,397.0,650.0,Labour,NaN,NaN,NaN,NaN
32,Margaret Thatcher,Conservative,1987-06-11,1990-11-28,1987-06-11,True,376.0,650.0,Labour,NaN,NaN,NaN,NaN
33,John Major,Conservative,1990-11-28,1992-04-09,1987-06-11,False,376.0,650.0,Labour,NaN,NaN,NaN,NaN
34,John Major,Conservative,1992-04-09,1997-05-02,1992-04-09,True,336.0,651.0,Labour,NaN,NaN,NaN,NaN
35,Tony Blair,Labour,1997-05-02,2001-06-07,1997-05-01,True,419.0,659.0,Conservative,NaN,NaN,NaN,NaN
36,Tony Blair,Labour,2001-06-07,2005-05-05,2001-06-07,True,413.0,659.0,Conservative,NaN,NaN,NaN,NaN
37,Tony Blair,Labour,2005-05-05,2007-06-27,2005-05-05,True,356.0,646.0,Conservative,NaN,NaN,NaN,NaN
38,Gordon Brown,Labour,2007-06-27,2010-05-11,2005-05-05,False,356.0,646.0,Conservative,NaN,NaN,NaN,NaN
39,David Cameron,Conservative,2010-05-11,2015-05-07,2010-05-06,True,363.0,650.0,Labour,NaN,Liberal Democrats,NaN,NaN
40,David Cameron,Conservative,2015-05-07,2016-07-13,2015-05-07,True,331.0,650.0,Labour,NaN,NaN,NaN,NaN
41,Theresa May,Conservative,2016-07-13,2017-06-08,2015-05-07,False,331.0,650.0,Labour,NaN,NaN,NaN,NaN
42,Theresa May,Conservative,2017-06-08,2019-07-24,2017-06-08,True,318.0,650.0,Labour,NaN,Democratic Unionist Party,NaN,NaN
43,Boris Johnson,Conservative,2019-07-24,2019-12-12,2017-06-08,False,318.0,650.0,Labour,NaN,Democratic Unionist Party,NaN,NaN
44,Boris Johnson,Conservative,2019-12-12,2022-09-06,2019-12-12,True,365.0,650.0,Labour,NaN,NaN,NaN,NaN
45,Liz Truss,Conservative,2022-09-06,2022-10-25,2019-12-12,False,365.0,650.0,Labour,NaN,NaN,NaN,NaN
46,Rishi Sunak,Conservative,2022-10-25,2024-07-05,2019-12-12,False,365.0,650.0,Labour,NaN,NaN,NaN,NaN
47,Keir Starmer,Labour,2024-07-05,NaN,2024-07-04,True,412.0,650.0,Conservative,NaN,NaN,NaN,NaN

In [67]:
# Asquith and Lloyd George pre-1918 - Liberal seats 1910
df_timeline.loc[0, 'seats_won'] = 274
df_timeline.loc[1, 'seats_won'] = 274

# MacDonald National Labour pre-election - inherited 1929 Labour seats
df_timeline.loc[10, 'seats_won'] = 288

# MacDonald National Labour post-election 1931 - full National Government coalition
df_timeline.loc[11, 'seats_won'] = 554

In [69]:
def calc_majority(row):
    if pd.notna(row['seats_won']) and pd.notna(row['total_seats']):
        return row['seats_won'] - (row['total_seats'] / 2 + 1)
    return None

df_timeline['majority'] = df_timeline.apply(calc_majority, axis=1)

display(df_timeline)

,pm,party,pm_start_date,pm_end_date,election_date,own_mandate,seats_won,total_seats,opposition_party,majority,coalition_parties,end_reason,notes
0,H. H. Asquith,Liberal,1910-12-19,1916-12-06,1910-12-19,True,274.0,670.0,Conservative,-62.0,NaN,NaN,NaN
1,David Lloyd George,Coalition Liberal,1916-12-06,1918-12-14,1910-12-19,False,274.0,670.0,Liberal,-62.0,"Conservative, Labour",NaN,NaN
2,David Lloyd George,Coalition Liberal,1918-12-14,1922-10-19,1918-12-14,True,521.0,707.0,Liberal,166.5,"Conservative, National Liberal",NaN,NaN
3,Bonar Law,Conservative,1922-10-23,1922-11-15,1918-12-14,False,383.0,707.0,Labour,28.5,NaN,NaN,NaN
4,Bonar Law,Conservative,1922-11-15,1923-05-20,1922-11-15,True,345.0,615.0,Labour,36.5,NaN,NaN,NaN
5,Stanley Baldwin,Conservative,1923-05-22,1923-12-06,1922-11-15,False,345.0,615.0,Labour,36.5,NaN,NaN,NaN
6,Stanley Baldwin,Conservative,1923-12-06,1924-01-22,1923-12-06,True,258.0,615.0,Labour,-50.5,NaN,NaN,NaN
7,Ramsay MacDonald,Labour,1924-01-22,1924-11-04,1923-12-06,False,191.0,615.0,Conservative,-117.5,NaN,NaN,NaN
8,Stanley Baldwin,Conservative,1924-11-04,1929-06-04,1924-10-29,True,419.0,615.0,Labour,110.5,NaN,NaN,NaN
9,Ramsay MacDonald,Labour,1929-06-05,1931-08-24,1929-05-30,True,288.0,615.0,Conservative,-20.5,NaN,NaN,NaN
10,Ramsay MacDonald,National Labour,1931-08-24,1931-10-27,1929-05-30,False,288.0,615.0,Labour,-20.5,NaN,NaN,NaN
11,Ramsay MacDonald,National Labour,1931-10-27,1935-06-07,1931-10-27,True,554.0,615.0,Labour,245.5,NaN,NaN,NaN
12,Stanley Baldwin,Conservative,1935-06-07,1935-11-14,1931-10-27,False,521.0,615.0,Labour,212.5,NaN,NaN,NaN
13,Stanley Baldwin,Conservative,1935-11-14,1937-05-28,1935-11-14,True,432.0,615.0,Labour,123.5,NaN,NaN,NaN
14,Neville Chamberlain,Conservative,1937-05-28,1940-05-10,1935-11-14,False,429.0,615.0,Labour,120.5,"National Labour, Liberal National",NaN,NaN
15,Winston Churchill,Conservative,1940-05-10,1945-07-26,1935-11-14,False,429.0,615.0,NaN,120.5,"Labour, Liberal National, Liberal, National La...",NaN,NaN
16,Clement Attlee,Labour,1945-07-26,1950-02-23,1945-07-05,True,393.0,640.0,Conservative,72.0,NaN,NaN,NaN
17,Clement Attlee,Labour,1950-02-23,1951-10-26,1950-02-23,True,315.0,625.0,Conservative,1.5,NaN,NaN,NaN
18,Winston Churchill,Conservative,1951-10-26,1955-04-05,1951-10-25,True,321.0,625.0,Labour,7.5,NaN,NaN,NaN
19,Anthony Eden,Conservative,1955-04-06,1955-05-26,1951-10-25,False,321.0,625.0,Labour,7.5,NaN,NaN,NaN
20,Anthony Eden,Conservative,1955-05-26,1957-01-09,1955-05-26,True,345.0,630.0,Labour,29.0,NaN,NaN,NaN
21,Harold Macmillan,Conservative,1957-01-10,1959-10-08,1955-05-26,False,345.0,630.0,Labour,29.0,NaN,NaN,NaN
22,Harold Macmillan,Conservative,1959-10-08,1963-10-18,1959-10-08,True,365.0,630.0,Labour,49.0,NaN,NaN,NaN
23,Alec Douglas-Home,Conservative,1963-10-19,1964-10-16,1959-10-08,False,365.0,630.0,Labour,49.0,NaN,NaN,NaN
24,Harold Wilson,Labour,1964-10-16,1966-03-31,1964-10-15,True,317.0,630.0,Conservative,1.0,NaN,NaN,NaN
25,Harold Wilson,Labour,1966-03-31,1970-06-19,1966-03-31,True,364.0,630.0,Conservative,48.0,NaN,NaN,NaN
26,Edward Heath,Conservative,1970-06-19,1974-03-04,1970-06-18,True,330.0,630.0,Labour,14.0,NaN,NaN,NaN
27,Harold Wilson,Labour,1974-03-04,1974-10-10,1974-02-28,True,301.0,635.0,Conservative,-17.5,NaN,NaN,NaN
28,Harold Wilson,Labour,1974-10-10,1976-04-05,1974-10-10,True,319.0,635.0,Conservative,0.5,NaN,NaN,NaN
29,James Callaghan,Labour,1976-04-05,1979-05-04,1974-10-10,False,319.0,635.0,Conservative,0.5,NaN,NaN,NaN
30,Margaret Thatcher,Conservative,1979-05-04,1983-06-09,1979-05-03,True,339.0,635.0,Labour,20.5,NaN,NaN,NaN
31,Margaret Thatcher,Conservative,1983-06-09,1987-06-11,1983-06-09,True,397.0,650.0,Labour,71.0,NaN,NaN,NaN
32,Margaret Thatcher,Conservative,1987-06-11,1990-11-28,1987-06-11,True,376.0,650.0,Labour,50.0,NaN,NaN,NaN
33,John Major,Conservative,1990-11-28,1992-04-09,1987-06-11,False,376.0,650.0,Labour,50.0,NaN,NaN,NaN
34,John Major,Conservative,1992-04-09,1997-05-02,1992-04-09,True,336.0,651.0,Labour,9.5,NaN,NaN,NaN
35,Tony Blair,Labour,1997-05-02,2001-06-07,1997-05-01,True,419.0,659.0,Conservative,88.5,NaN,NaN,NaN
36,Tony Blair,Labour,2001-06-07,2005-05-05,2001-06-07,True,413.0,659.0,Conservative,82.5,NaN,NaN,NaN
37,Tony Blair,Labour,2005-05-05,2007-06-27,2005-05-05,True,356.0,646.0,Conservative,32.0,NaN,NaN,NaN
38,Gordon Brown,Labour,2007-06-27,2010-05-11,2005-05-05,False,356.0,646.0,Conservative,32.0,NaN,NaN,NaN
39,David Cameron,Conservative,2010-05-11,2015-05-07,2010-05-06,True,363.0,650.0,Labour,37.0,Liberal Democrats,NaN,NaN
40,David Cameron,Conservative,2015-05-07,2016-07-13,2015-05-07,True,331.0,650.0,Labour,5.0,NaN,NaN,NaN
41,Theresa May,Conservative,2016-07-13,2017-06-08,2015-05-07,False,331.0,650.0,Labour,5.0,NaN,NaN,NaN
42,Theresa May,Conservative,2017-06-08,2019-07-24,2017-06-08,True,318.0,650.0,Labour,-8.0,Democratic Unionist Party,NaN,NaN
43,Boris Johnson,Conservative,2019-07-24,2019-12-12,2017-06-08,False,318.0,650.0,Labour,-8.0,Democratic Unionist Party,NaN,NaN
44,Boris Johnson,Conservative,2019-12-12,2022-09-06,2019-12-12,True,365.0,650.0,Labour,39.0,NaN,NaN,NaN
45,Liz Truss,Conservative,2022-09-06,2022-10-25,2019-12-12,False,365.0,650.0,Labour,39.0,NaN,NaN,NaN
46,Rishi Sunak,Conservative,2022-10-25,2024-07-05,2019-12-12,False,365.0,650.0,Labour,39.0,NaN,NaN,NaN
47,Keir Starmer,Labour,2024-07-05,NaN,2024-07-04,True,412.0,650.0,Conservative,86.0,NaN,NaN,NaN

In [70]:
print(df_timeline['own_mandate'].dtype)
print(df_timeline['own_mandate'].unique())

bool
[ True False]

In [71]:
df_timeline.to_json('government_timeline.json', orient='records', indent=4)

In [73]:
print(df)

   election_date  total_seats  con_votes  con_seats  lab_votes  lab_seats  \
0     1910-12-19          670       46.3        272        7.2         42
1     1918-12-14          707       38.7        383       23.7         73
2     1922-11-15          615       38.2        345       29.5        142
3     1923-12-06          615       38.1        258       30.5        191
4     1924-10-29          615       48.3        419       33.0        151
5     1929-05-30          615       38.2        260       37.1        288
6     1931-10-27          615       60.6        521       30.6         52
7     1935-11-14          615       53.7        432       37.9        154
8     1945-07-05          640       39.8        213       47.8        393
9     1950-02-23          625       43.5        298       46.1        315
10    1951-10-25          625       48.0        321       48.7        295
11    1955-05-26          630       49.7        345       46.2        277
12    1959-10-08          630       49.4        365       43.7        258
13    1964-10-15          630       43.4        304       43.8        317
14    1966-03-31          630       41.8        253       47.8        364
15    1970-06-18          630       46.4        330       42.7        288
16    1974-02-28          635       37.9        297       37.1        301
17    1974-10-10          635       35.9        277       39.3        319
18    1979-05-03          635       43.9        339       36.9        269
19    1983-06-09          650       42.4        397       27.6        209
20    1987-06-11          650       42.3        376       30.8        229
21    1992-04-09          651       41.8        336       34.4        271
22    1997-05-01          659       30.7        165       43.3        419
23    2001-06-07          659       31.7        166       40.7        413
24    2005-05-05          646       32.3        198       35.2        356
25    2010-05-06          650       36.1        307       29.0        258
26    2015-05-07          650       36.9        331       30.4        232
27    2017-06-08          650       42.4        318       40.0        262
28    2019-12-12          650       43.6        365       32.1        203
29    2024-07-04          650       23.7        121       33.8        412

    lib_votes  lib_seats  oth_votes  oth_seats  \
0        43.8        272        2.7         84
1        25.6        161       12.0         90
2        29.1        116        3.2         12
3        29.6        159        1.8          7
4        17.6         40        1.1          5
5        23.4         59        1.3          8
6         7.0         37        1.7          5
7         6.4         20        2.0          9
8         9.0         12        3.4         22
9         9.1          9        1.3          3
10        2.5          6        0.7          3
11        2.7          6        1.3          2
12        5.9          6        1.1          1
13       11.1          9        1.7          0
14        8.4         12        2.0          1
15        7.4          6        3.5          6
16       19.3         14        5.6         23
17       18.3         13        6.6         26
18       13.8         11        5.4         16
19       25.4         23        4.6         21
20       22.6         22        4.3         23
21       17.8         20        6.0         24
22       16.8         46        9.3         29
23       18.3         52        9.3         28
24       22.0         62       10.4         30
25       23.0         57       11.9         28
26        7.9          8       24.8         79
27        7.4         12       10.2         58
28       11.6         11       12.7         71
29       12.2         72       30.3         45

                                              comment
0   Repeat election forced by George V to legitimi...
1         Lloyd George (Lib) leads coalition with Con
2   Bonar Law (Con) breaks the coalition, Labour o...
3   Ramsay MacDonald (Lab) with Lib-coalition beat...
4   Baldwin (Con) elected after Liberals bring dow...
5   Ramsay MacDonald (Lab) minority govt with Lib ...
6   National Govt (Con plus some Lib and Lab) unde...
7       National Govt led by Baldwin (Con) re-elected
8   Attlee (Lab) beats Churchill (Con) in post-war...
9         Attlee (Lab) beats Churchill (Con) narrowly
10  Churchill (Con) beats Attlee (Lab) after econo...
11          Eden (Con) beats Attlee (Lab) comfortably
12  Macmillan (Con) beats Gaitskell (Lab) with str...
13  Wilson (Lab) narrowly beats Douglas-Home (Con)...
14  Wilson (Lab) beats Heath (Con) with strong maj...
15  Heath (Con) beats Wilson (Lab), surprising the...
16  Wilson (Lab) minority govt after industrial di...
17  Repeat election gives Wilson (Lab) a tiny majo...
18  Thatcher (Con) beats Callaghan (Lab) after ind...
19  Thatcher (Con) landslide over Foot (Lab) after...
20  Thatcher (Con) landslide over Kinnock (Lab) an...
21      Major (Con) narrow victory over Kinnock (Lab)
22             Blair (Lab) landslide over Major (Con)
23             Blair (Lab) landslide over Hague (Con)
24  Blair (Lab) beats Howard (Con), with reduced m...
25        Cameron (Con) leads coalition with Lib Dems
26  Cameron (Con) beats Miliband (Lab) to get a sl...
27        May (Con) minority govt after EU Referendum
28  Johnson (Con) beats Corbyn (Lab) with strong m...
29           Starmer (Lab) landslide over Sunak (Con)

In [74]:
import json, re
from pathlib import Path

timeline = json.loads(Path("government_timeline.json").read_text())
raw      = Path("text.txt").read_text()
blocks   = [b.strip() for b in re.split(r'\n\s*\n', raw) if b.strip()]

# Build lookup keyed on (pm_name, start_date)
lookup = {}
for block in blocks:
    hm = re.match(r'^(.+?)\s+\((\d{4}-\d{2}-\d{2})\s+to\s+', block)
    if not hm:
        continue
    rm = re.search(r'^End Reason:\s*(.+)$', block, re.MULTILINE)
    nm = re.search(r'^Notes:\s*(.+)$',      block, re.MULTILINE)
    end_reason = rm.group(1).strip() if rm else None
    if end_reason and end_reason.upper() in ("N/A", "NA"):
        end_reason = None
    lookup[(hm.group(1).strip(), hm.group(2))] = {
        "end_reason": end_reason,
        "notes":      nm.group(1).strip() if nm else None
    }

for row in timeline:
    entry = lookup.get((row["pm"], row["pm_start_date"]))
    if entry:
        row.update(entry)

Path("government_timeline.json").write_text(json.dumps(timeline, indent=4))
print(f"Done. {sum(1 for r in timeline if r.get('end_reason'))}/{len(timeline)} filled.")

Done. 47/48 filled.